apiVersion: v1
kind: ContinuousQuery
name: risky-running-workloads
spec:
  mode: query
  sources:
    subscriptions:
      - id: nopollops-postgres
        nodes:
          - sourceLabel: app_submissions
          - sourceLabel: risky_images
    joins:
      - id: HAS_RISK
        keys:
          - label: app_submissions
            property: image
          - label: risky_images
            property: image
  query: >
    MATCH
      (submission:app_submissions)-[:HAS_RISK]->(risk:risky_images)
    WHERE
      risk.active = 't'
      AND submission.status <> 'deleted'
    RETURN
      submission.id AS submissionId,
      submission.app_name AS appName,
      submission.team_name AS teamName,
      submission.namespace AS namespace,
      submission.deployment_name AS deploymentName,
      submission.image AS image,
      submission.status AS status,
      risk.severity AS severity,
      risk.reason AS reason,
      risk.mitigation AS mitigation
