apiVersion: v1
kind: Source
name: nopollops-postgres
spec:
  kind: PostgreSQL
  properties:
    host: ${POSTGRES_HOST}
    port: 5432
    user:
      kind: Secret
      name: pg-creds
      key: user
    password:
      kind: Secret
      name: pg-creds
      key: password
    database: nopollops
    ssl: true
    tables:
      - public.participants
      - public.app_submissions
      - public.risky_images
      - public.remediation_votes
---
apiVersion: v1
kind: Source
name: nopollops-kubernetes
spec:
  kind: Kubernetes
  properties:
    kubeConfig:
      kind: Secret
      name: k8s-context
      key: context

