apiVersion: v1
kind: Reaction
name: nopollops-http
spec:
  kind: Http
  queries:
    risky-running-workloads:
      url: http://nopollops-api.nopollops-system.svc.cluster.local:8080/api/drasi/reactions
      method: POST
    affected-teams:
      url: http://nopollops-api.nopollops-system.svc.cluster.local:8080/api/drasi/reactions
      method: POST

